
export enum Portal {
  SL = 'SL',
  LI = 'LI',
  LR = 'LR',
  BD = 'BD',
  BUCOM = 'BUCOM',
  IWB = 'IWB',
  IWT = 'IWT',
  IMMONET = 'IMMONET',
}

export enum DistributionType {
  BUY = 'BUY',
  RENT = 'RENT',
  COMPULSORY_AUCTION = 'COMPULSORY_AUCTION',
  BUY_AUCTION = 'BUY_AUCTION',
  BUY_RENT = 'BUY_RENT',
}

export enum KitchenEquipment {
  NONE = 'NONE',
  STORAGE = 'STORAGE',
  FULLY_EQUIPPED = 'FULLY_EQUIPPED',
}

export enum ExtendedValidation {
  PART = 'PART',
  FULL = 'FULL',
  NO = 'NO',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum BuildState {
  FIRST_TIME_USE = 'FIRST_TIME_USE',
  FIRST_TIME_USE_AFTER_REFURBISHMENT = 'FIRST_TIME_USE_AFTER_REFURBISHMENT',
  MINT_CONDITION = 'MINT_CONDITION',
  MODERNISED = 'MODERNISED',
  REFURBISHED = 'REFURBISHED',
  FULLY_RENOVATED = 'FULLY_RENOVATED',
  PARTLY_RENOVATED = 'PARTLY_RENOVATED',
  NEED_OF_RENOVATION = 'NEED_OF_RENOVATION',
  WELL_KEPT = 'WELL_KEPT',
  NEGOTIABLE = 'NEGOTIABLE',
  RIPE_FOR_DEMOLITION = 'RIPE_FOR_DEMOLITION',
  PROJECTED = 'PROJECTED',
  NO_INFORMATION = 'NO_INFORMATION',
  RESTRUCTURED = 'RESTRUCTURED',
}

export enum Validation {
  YES = 'YES',
  NO = 'NO',
  PART = 'PART',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum Features {
  KITCHEN_FULLY_EQUIPPED = 'KITCHEN_FULLY_EQUIPPED',
  GARDEN = 'GARDEN',
  BATHROOM_WINDOW = 'BATHROOM_WINDOW',
  PARKING_GARAGE = 'PARKING_GARAGE',
  BALCONY_TERRACE = 'BALCONY_TERRACE',
  REDUCE_MOBILITY_ACCESS = 'REDUCE_MOBILITY_ACCESS',
  PETS_ALLOWED = 'PETS_ALLOWED',
  VACANT = 'VACANT',
  CELLAR = 'CELLAR',
  BATHTUB = 'BATHTUB',
  ELEVATOR = 'ELEVATOR',
  COMMISSION_FREE = 'COMMISSION_FREE',
  NO_MEDIA = 'NO_MEDIA',
}

export enum MarketStatus {
  SOLD = 'SOLD',
  RENTED = 'RENTED',
  REFERENCE = 'REFERENCE',
  RESERVED = 'RESERVED',
  UNDER_OFFER = 'UNDER_OFFER',
}

export enum UseFor {
  LIVING = 'LIVING',
  COMMERCIAL = 'COMMERCIAL',
  MIXED = 'MIXED',
  OFFICE = 'OFFICE',
  INDUSTRIAL = 'INDUSTRIAL',
}

export enum EstateSubType {
  LIVING = 'LIVING',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRY = 'INDUSTRY',
  AGRICULTURE_FORESTRY = 'AGRICULTURE_FORESTRY',
  MIXED = 'MIXED',
  LEISURE_FACILITY = 'LEISURE_FACILITY',
  COMMERCIAL_PARC = 'COMMERCIAL_PARC',
  SPECIAL_USE = 'SPECIAL_USE',
  LAKESIDE_PROPERTY = 'LAKESIDE_PROPERTY',
}

export enum EstateType {
  PLOT = 'PLOT',
  PARKING = 'PARKING',
  MISCELLANEOUS = 'MISCELLANEOUS',
}

export enum ProjectType {
  RESALE = 'RESALE',
  NEW_BUILD = 'NEW_BUILD',
  INVESTMENT = 'INVESTMENT',
  SHORT_TIME_RENTAL = 'SHORT_TIME_RENTAL',
  FLATSHARING = 'FLATSHARING',
  STOCK = 'STOCK',
  PROJECTED = 'PROJECTED',
}