environment                        = "preview"
classified_management_sync_bucket  = "aviv-classdisp-preview-stage-resync-bucket"
classified_management_events_topic = "arn:aws:sns:eu-west-1:821590770219:classdisp-stage-dispatch-classified-event-topic"
classified_management_api          = "https://classmgt-stage-api.kind-camel-preview.aws.aviv-internal.eu"
aws_account_name                   = "crazy-penguin-preview"
geo_places_api_url                 = "https://place-api.cosmic-bullfrog-preview.aws.aviv.eu/"
