version: 2.1

parameters:
  run-http-api-standards-job:
    type: boolean
    default: false
  run-classified-management-connector-job:
    type: boolean
    default: false
aliases:
  - &devfilter
    filters:
      branches:
        ignore: main
  - &previewfilter
    filters:
      branches:
        only: main
        ignore: /.*/
  - &livefilter
    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*/
      branches:
        ignore: /.*/
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-s3: circleci/aws-s3@3.1.1
  terraform: circleci/terraform@3.2.1

jobs:
  build-classified-management-connector:
    docker:
      - image: cimg/node:20.11.0
    parameters:
      ENV_SECRETS:
        type: string
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare --activate
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID_<<parameters.ENV_SECRETS>>
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_<<parameters.ENV_SECRETS>>
      - run:
          name: Install Dependencies
          command: pnpm install --no-frozen-lockfile
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: pnpm -C src/ run test
      - run:
          name: Build
          command: pnpm -C src/ run build:lambdas
      - persist_to_workspace:
          paths:
            - "."
          root: "~/project"
            
  deploy-classified-management-connector:
    executor: 
      name: terraform/default
      tag: "1.5.7"
    parameters:
      ENV:
        type: string
      ENV_PATH_FILE:
        type: string
      ENV_SECRETS:
        type: string
    working_directory: ~/project
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID_<<parameters.ENV_SECRETS>>
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY_<<parameters.ENV_SECRETS>>
      - attach_workspace:
          at: ./
      - terraform/init:
          path: ./infra
          backend_config: "backend.<<parameters.ENV>>.tfvars"
      - terraform/plan:
          path: ./infra
          var_file: <<parameters.ENV_PATH_FILE>>
      - terraform/apply:
          path: ./infra
          var_file: <<parameters.ENV_PATH_FILE>>

workflows:
  classified-management-connector-dev:
    when: << pipeline.parameters.run-classified-management-connector-job >>
    jobs:
      - build-classified-management-connector:
          <<: *devfilter
          ENV_SECRETS: "DEV"
      - deploy-classified-management-connector:
          <<: *devfilter
          ENV: "dev"
          ENV_SECRETS: "DEV"
          ENV_PATH_FILE: "./dev.tfvars"
          requires:
            - build-classified-management-connector
  classified-management-connector-preview:
    when: << pipeline.parameters.run-classified-management-connector-job >>
    jobs:
      - build-classified-management-connector:
            ENV_SECRETS: "PREVIEW"
            <<: *previewfilter
      - deploy-classified-management-connector:
            <<: *previewfilter
            ENV: "preview"
            ENV_SECRETS: "PREVIEW"
            ENV_PATH_FILE: "./preview.tfvars"
            requires:
              - build-classified-management-connector
  classified-management-connector-live:
    jobs:
      - build-classified-management-connector:
          ENV_SECRETS: "LIVE"
          <<: *livefilter
      - promote:
          <<: *livefilter
          name: Approve deploy to prod 
          type: approval
          requires:
            - build-classified-management-connector
      - deploy-classified-management-connector:
          <<: *livefilter
          ENV: "live"
          ENV_SECRETS: "LIVE"
          ENV_PATH_FILE: "./live.tfvars"
          requires:
            - build-classified-management-connector
