export interface ClassifiedWithFullGeo {
    classifiedId: string;
    estatetype: string;
    estatesubtype: string;
    distributiontype: string;
    location_type: string;
    country: string;
    city: string;
    postalcode: string;
    price: number;
    numberofrooms: number;
    furnished: string;
    yearofconstruction: string;
    certificateofeligibilityneeded: string;
    locationinbuilding: string;
    features: string;
    isauthorized: string;
    isgeodatavalid: string;
    ismarketstatuseligibleforpublication: string;
    geolevel: string;
    livingspace: number;
    overallspace: number;
    blocid: string;
    projecttypes: string;
    brand: string;
    portals: string;
    portal: string;
    geo_avivgeoid: string;
    showaddress: boolean;
    street: string;
    showPrice: boolean;
    isRangePrice: boolean;
    space: number;
    businessSubType: string;
    building_offeredFloors:number;
    hideneighborhood: boolean;
    geoprecision?: string | null;
    placeids?: string[] | null;
    place_ad02?: string[] | null;
    place_ad03?: string[] | null;
    place_ad04?: string[] | null;
    place_ad05?: string[] | null;
    place_ad06?: string[] | null;
    place_ad08?: string[] | null;
    place_ad09?: string[] | null;
    place_nbh1?: string[] | null;
    place_nbh2?: string[] | null;
    place_nbh3?: string[] | null;
    place_stu3?: string[] | null;
    place_bloc?: string[] | null;
    place_strt?: string[] | null;
    place_honu?: string[] | null;
    externalid?: string;
    updateDate?: Date;
    creationdate?: Date;
}