export interface ClassifiedWithFullGeo {
    classifiedId: string;
    estatetype: string;
    estatesubtype: string;
    distributiontype: string;
    avivgeoid: string;
    location_type: string;
    country: string;
    city: string;
    postalcode: string;
    price: number;
    numberofrooms: number;
    furnished: string;
    yearofconstruction: string;
    certificateofeligibilityneeded: string;
    locationinbuilding: string;
    features: string;
    isauthorized: string;
    isgeodatavalid: string;
    ismarketstatuseligibleforpublication: string;
    geolevel: string;
    countryid: string;
    regionid: string;
    microregionid: string;
    provinceid: string;
    municipalityid: string;
    municipalityname: any;
    boroughid: string;
    neighborhoodid: string;
    neighborhoodname: any;
    livingspace: number;
    blocid: string;
    projecttypes: string;
    brand: string;
    portals: string;
    portal: string;
    geo_avivgeoid: string;
    showaddress: string,
    street: string
}