export interface ClassifiedWithFullGeo {
    classifiedId: string;
    estatetype: string;
    estatesubtype: string;
    distributiontype: string;
    avivgeoid: string;
    location_type: string;
    country: string;
    city: string;
    postalcode: string;
    price: number;
    numberofrooms: number;
    furnished: string;
    yearofconstruction: string;
    certificateofeligibilityneeded: string;
    locationinbuilding: string;
    features: string;
    isauthorized: string;
    isgeodatavalid: string;
    ismarketstatuseligibleforpublication: string;
    geolevel: number;
    countryid: number;
    regionid: number;
    microregionid: number;
    provinceid: number;
    municipalityid: number;
    municipalityname: string;
    boroughid: number;
    neighborhoodid: number;
    neighborhoodname: string;
    livingspace: number;
    blocid: number;
    projecttypes: string;
    brand: string;
    portals: string;
    portal: string;
    geo_avivgeoid: number;
    showaddress: string,
    street: string
}