export const enum EstateType {
    'HOUSE' = 'HOUSE',
    'APARTMENT' = 'APARTMENT',
    'PLOT' = 'PLOT',
    'OFFICE' = 'OFFICE',
    'TRADING' = 'TRADING',
    'GASTRONOMY_HOTEL' = 'GASTRONOMY_HOTEL',
    'STORAGE_PRODUCTION' = 'STORAGE_PRODUCTION',
    'AGRICULTURE_FORESTRY' = 'AGRICULTURE_FORESTRY',
    'PARKING' = 'PARKING',
    'SENIOR' = 'SENIOR',
    'PROJECT' = 'PROJECT',
    'MISCELLANEOUS' = 'MISCELLANEOUS',
  }