export enum Portal {
  SL = 'SL',
  LI = 'LI',
  LR = 'LR',
  BD = 'BD',
  BUCOM = 'BUCOM',
  IWB = 'IWB',
  IWT = 'IWT',
  IMMONET = 'IMMONET',
  SLN = 'SLN',
  LIN = 'LIN',
  SLC = 'SLC',
}

export enum BrandCountry {
  FR = 'FR',
  DE = 'DE',
  AT = 'AT',
}

export enum DistributionType {
  BUY = 'BUY',
  RENT = 'RENT',
  COMPULSORY_AUCTION = 'COMPULSORY_AUCTION',
  BUY_AUCTION = 'BUY_AUCTION',
  BUY_RENT = 'BUY_RENT',
}

export enum DistributionSubTypeBuy {
  BUSINESS_LEASEBACK = 'BUSINESS_LEASEBACK',
  BUSINESS_SALE_GOODWILL = 'BUSINESS_SALE_GOODWILL',
  RESALE = 'RESALE',
  LIFE_ANNUITY = 'LIFE_ANNUITY',
  NEW_BUILD_INVESTMENT_PRODUCT = 'NEW_BUILD_INVESTMENT_PRODUCT',
  NEW_BUILD_PROJECT = 'NEW_BUILD_PROJECT',
  NEW_BUILD_UNIT = 'NEW_BUILD_UNIT',
  NEW_HOME = 'NEW_HOME',
}

export enum DistributionSubTypeRent {
  BUSINESS = 'BUSINESS',
  CLASSIC = 'CLASSIC',
  TEMPORARY = 'TEMPORARY',
  VACATION = 'VACATION',
  NEW_BUILD_PROJECT = 'NEW_BUILD_PROJECT',
}

export enum KitchenEquipment {
  NONE = 'NONE',
  STORAGE = 'STORAGE',
  FULLY_EQUIPPED = 'FULLY_EQUIPPED',
}

export enum ExtendedValidation {
  PART = 'PART',
  FULL = 'FULL',
  NO = 'NO',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum BuildState {
  FIRST_TIME_USE = 'FIRST_TIME_USE',
  FIRST_TIME_USE_AFTER_REFURBISHMENT = 'FIRST_TIME_USE_AFTER_REFURBISHMENT',
  MINT_CONDITION = 'MINT_CONDITION',
  MODERNISED = 'MODERNISED',
  REFURBISHED = 'REFURBISHED',
  FULLY_RENOVATED = 'FULLY_RENOVATED',
  PARTLY_RENOVATED = 'PARTLY_RENOVATED',
  NEED_OF_RENOVATION = 'NEED_OF_RENOVATION',
  WELL_KEPT = 'WELL_KEPT',
  NEGOTIABLE = 'NEGOTIABLE',
  RIPE_FOR_DEMOLITION = 'RIPE_FOR_DEMOLITION',
  PROJECTED = 'PROJECTED',
  NO_INFORMATION = 'NO_INFORMATION',
  RESTRUCTURED = 'RESTRUCTURED',
}

export enum Validation {
  YES = 'YES',
  NO = 'NO',
  PART = 'PART',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum SwimmingPool {
  YES = 'YES',
  NO = 'NO',
  OUTSIDE = 'OUTSIDE',
  INSIDE_AND_OUTSIDE = 'INSIDE_AND_OUTSIDE',
  INSIDE = 'INSIDE',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum MandateType {
  DIRECT = 'DIRECT',
  EXCLUSIVE = 'EXCLUSIVE',
  SIMPLE = 'SIMPLE',
}

export enum Features {
  KITCHEN_FULLY_EQUIPPED = 'KITCHEN_FULLY_EQUIPPED',
  GARDEN = 'GARDEN',
  BATHROOM_WINDOW = 'BATHROOM_WINDOW',
  PARKING_GARAGE = 'PARKING_GARAGE',
  BALCONY_TERRACE = 'BALCONY_TERRACE',
  REDUCE_MOBILITY_ACCESS = 'REDUCE_MOBILITY_ACCESS',
  PETS_ALLOWED = 'PETS_ALLOWED',
  VACANT = 'VACANT',
  CELLAR = 'CELLAR',
  BATHTUB = 'BATHTUB',
  ELEVATOR = 'ELEVATOR',
  COMMISSION_FREE = 'COMMISSION_FREE',
  NO_MEDIA = 'NO_MEDIA',
  BOOKING_EFFECTS_SUGGESTION = 'BOOKING_EFFECTS_SUGGESTION',
  SWIMMING_POOL = 'SWIMMING_POOL',
  EXCLUSIVE = 'EXCLUSIVE',
  ASSISTED_LIVING = 'ASSISTED_LIVING',
  AIR_CONDITION = 'AIR_CONDITION',
  HOUSEBOAT = 'HOUSEBOAT',
}

export enum Effect {
  SUGGESTION = 'SUGGESTION',
  TOP_POSITION = 'TOP_POSITION',
}

export enum MarketStatus {
  SOLD = 'SOLD',
  RENTED = 'RENTED',
  REFERENCE = 'REFERENCE',
  RESERVED = 'RESERVED',
  UNDER_OFFER = 'UNDER_OFFER',
}

export enum UseFor {
  LIVING = 'LIVING',
  COMMERCIAL = 'COMMERCIAL',
  MIXED = 'MIXED',
  OFFICE = 'OFFICE',
  INDUSTRIAL = 'INDUSTRIAL',
}

export enum EstateSubType {
  LIVING = 'LIVING',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRY = 'INDUSTRY',
  AGRICULTURE_FORESTRY = 'AGRICULTURE_FORESTRY',
  MIXED = 'MIXED',
  LEISURE_FACILITY = 'LEISURE_FACILITY',
  COMMERCIAL_PARC = 'COMMERCIAL_PARC',
  SPECIAL_USE = 'SPECIAL_USE',
  LAKESIDE_PROPERTY = 'LAKESIDE_PROPERTY',
  FLATSHARING_ROOM = 'FLATSHARING_ROOM',
}

export enum EstateType {
  HOUSE = 'HOUSE',
  APARTMENT = 'APARTMENT',
  PARKING = 'PARKING',
  MISCELLANEOUS = 'MISCELLANEOUS',
  OFFICE = 'OFFICE',
  PLOT = 'PLOT',
  PROJECT = 'PROJECT',
}

export enum ProjectType {
  RESALE = 'RESALE',
  NEW_BUILD = 'NEW_BUILD',
  INVESTMENT = 'INVESTMENT',
  SHORT_TIME_RENTAL = 'SHORT_TIME_RENTAL',
  FLATSHARING = 'FLATSHARING',
  STOCK = 'STOCK',
  PROJECTED = 'PROJECTED',
  SWAP_APARTMENT = 'SWAP_APARTMENT',
  LIFE_ANNUITY = 'LIFE_ANNUITY',
}

export enum ClassifiedBusiness {
  PRIVATE = 'PRIVATE',
  PROFESSIONAL = 'PROFESSIONAL',
  PROFESSIONAL_UNITARY = 'PROFESSIONAL_UNITARY',
}

export enum EnrichmentType {
  FRAUD = 'FRAUD',
  GEO = 'GEO',
}

export enum HeatMethod {
  CENTRAL = 'CENTRAL',
  INDIVIDUAL = 'INDIVIDUAL',
  STOREY = 'STOREY',
}

export enum HeatForm {
  AIR = 'AIR',
  RADIATOR = 'RADIATOR',
  STOVE = 'STOVE',
  UNDERFLOOR = 'UNDERFLOOR',
  WALL_CEILING = 'WALL_CEILING',
  MIXED = 'MIXED',
}

export enum EnergySource {
  COAL = 'COAL',
  DISTRICT_HEATING = 'DISTRICT_HEATING',
  ELECTRIC = 'ELECTRIC',
  GAS = 'GAS',
  GEOTHERMAL = 'GEOTHERMAL',
  LIQUID_GAS = 'LIQUID_GAS',
  OIL = 'OIL',
  SOLAR_HEAT = 'SOLAR_HEAT',
  SOLAR_POWER = 'SOLAR_POWER',
  WIND = 'WIND',
  WOOD = 'WOOD',
  WOOD_PELLET = 'WOOD_PELLET',
  THERMIC_PANELS = 'THERMIC_PANELS',
  PHOTOVOLTAIC_PANELS = 'PHOTOVOLTAIC_PANELS',
}

export enum EnergyGeneration {
  FOSSIL_BURNING = 'FOSSIL_BURNING',
  HEAT_PUMP = 'HEAT_PUMP',
  COMBINED_HEAT_AND_POWER_PLANT = 'COMBINED_HEAT_AND_POWER_PLANT',
}

export enum AddressDisplayPreference {
  EXACT_POINT = 'EXACT_POINT',
  NEIGHBORHOOD = 'NEIGHBORHOOD',
  CITY = 'CITY',
}

export enum PriceInformation {
  PRICE_ON_DEMAND = 'PRICE_ON_DEMAND',
}
